// Frontend/src/Components/Dashboard/Home.jsx
import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { AlertCircle, RefreshCw, Send, X } from "lucide-react";
import { useLocation } from "react-router-dom";

import AppSidebar from "../app-sidebar";
import AIInsights from "./AIInsights";
import Navbar from "./Navbar";
import RecentTransactions from "./RecentTransactions";
import SpendingChart from "./SpendingChart";
import StatsCards from "./StatsCards";
import TransactionHistory from "./TransactionHistory";
import OpenAccount from "./OpenAccount";
import KYCVerification from "./KYCVerification";
import AdminPanel from "./AdminPanel";
import ProfileView from "./ProfileView";
import SettingsView from "./SettingsView";
import GoalsView from "./GoalsView";

import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar";

const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:3000";

const emptyDashboard = {
  user: {},
  summary: {
    totalBalance: 0,
    totalIncome: 0,
    totalExpense: 0,
    ONEO_BankCoins: 0,
    totalAccounts: 0,
    notificationCount: 0,
    balanceChange: 0,
    incomeChange: 0,
    expenseChange: 0,
    coinsChange: 0,
  },
  recentTransactions: [],
  analytics: {
    totalExpense: 0,
    categories: [],
  },
  aiInsights: {
    headline: "Your activity is ready to grow",
    message: "Live insights appear as your YONO App account activity grows.",
    savingsPotential: 0,
    items: [],
  },
};

function readStoredUser() {
  try {
    return JSON.parse(sessionStorage.getItem("YONO AppUser")) || {};
  } catch {
    return {};
  }
}

function mergeDashboard(payload) {
  return {
    ...emptyDashboard,
    ...payload,
    summary: {
      ...emptyDashboard.summary,
      ...(payload?.summary || {}),
    },
    analytics: {
      ...emptyDashboard.analytics,
      ...(payload?.analytics || {}),
    },
    aiInsights: {
      ...emptyDashboard.aiInsights,
      ...(payload?.aiInsights || {}),
      items: payload?.aiInsights?.items || emptyDashboard.aiInsights.items,
    },
    recentTransactions: payload?.recentTransactions || [],
  };
}

function DashboardSkeleton() {
  return (
    <div className="space-y-5">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {Array.from({ length: 4 }).map((_, index) => (
          <div
            className="h-32 animate-pulse rounded-lg border border-slate-200 bg-white shadow-sm"
            key={index}
          />
        ))}
      </div>
      <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
        <div className="h-96 animate-pulse rounded-lg border border-slate-200 bg-white shadow-sm" />
        <div className="h-96 animate-pulse rounded-lg border border-slate-200 bg-white shadow-sm" />
      </div>
    </div>
  );
}

const Home = () => {
  const location = useLocation();
  const storedUser = useMemo(() => readStoredUser(), []);
  const fallbackUser = useMemo(
    () => ({
      ...storedUser,
      email: storedUser.email || location.state?.email,
    }),
    [location.state?.email, storedUser],
  );

  const [dashboard, setDashboard] = useState(() => ({
    ...emptyDashboard,
    user: fallbackUser,
  }));
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const [activeView, setActiveView] = useState("dashboard");

  const [isDarkMode, setIsDarkMode] = useState(() => {
    const savedSettings = localStorage.getItem("yono_settings");
    if (savedSettings) {
      try {
        const parsed = JSON.parse(savedSettings);
        if (parsed.darkMode) {
          return localStorage.getItem("yono_theme") === "dark";
        }
      } catch (e) {
        // ignore
      }
    }
    return false;
  });

  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [isDarkMode]);

  const handleToggleDarkMode = () => {
    setIsDarkMode((prev) => {
      const next = !prev;
      const savedSettings = localStorage.getItem("yono_settings");
      if (savedSettings) {
        try {
          const parsed = JSON.parse(savedSettings);
          if (parsed.darkMode) {
            localStorage.setItem("yono_theme", next ? "dark" : "light");
          }
        } catch (e) {
          // ignore
        }
      }
      return next;
    });
  };

  // Send Money modal state
  const [showSendModal, setShowSendModal] = useState(false);
  const [userAccounts, setUserAccounts] = useState([]);
  const [sendForm, setSendForm] = useState({
    FromAccount: "",
    toAccount: "",
    amount: "",
  });
  const [sendLoading, setSendLoading] = useState(false);
  const [sendError, setSendError] = useState("");
  const [sendSuccess, setSendSuccess] = useState("");

  // Fetch user accounts for the FromAccount dropdown
  const fetchAccounts = useCallback(async () => {
    try {
      const res = await axios.get(`${API_BASE_URL}/api/account`, {
        withCredentials: true,
      });
      const accounts = res.data?.accounts || [];
      setUserAccounts(accounts);
      if (accounts.length === 1) {
        setSendForm((prev) => ({ ...prev, FromAccount: accounts[0]._id }));
      }
    } catch {
      // Silently fail — accounts will show empty
    }
  }, []);

  const handleSendMoney = async (e) => {
    e.preventDefault();
    setSendLoading(true);
    setSendError("");
    setSendSuccess("");

    try {
      const idempotencyKey = crypto.randomUUID();
      const res = await axios.post(
        `${API_BASE_URL}/api/transaction`,
        {
          FromAccount: sendForm.FromAccount,
          toAccount: sendForm.toAccount,
          amount: Number(sendForm.amount),
          idempotencyKey,
        },
        { withCredentials: true }
      );
      setSendSuccess(res.data?.message || "Transaction successful!");
      setSendForm({ FromAccount: userAccounts.length === 1 ? userAccounts[0]._id : "", toAccount: "", amount: "" });
      // Refresh dashboard after successful transaction
      fetchDashboard();
    } catch (err) {
      setSendError(err.response?.data?.message || "Transaction failed. Please try again.");
    } finally {
      setSendLoading(false);
    }
  };

  const openSendModal = () => {
    setSendError("");
    setSendSuccess("");
    setShowSendModal(true);
    fetchAccounts();
  };

  const fetchDashboard = useCallback(async () => {
    setError("");
    setRefreshing(true);

    try {
      const response = await axios.get(`${API_BASE_URL}/api/dashboard`, {
        withCredentials: true,
      });
      setDashboard(mergeDashboard(response.data));
    } catch (requestError) {
      // Fallback: try to build dashboard from account data
      try {
        const accountsResponse = await axios.get(`${API_BASE_URL}/api/account`, {
          withCredentials: true,
        });
        const accounts = accountsResponse.data?.accounts || [];
        const accountsWithBalance = await Promise.all(
          accounts.map(async (account) => {
            try {
              const balanceResponse = await axios.get(
                `${API_BASE_URL}/api/account/balance/${account._id}`,
                { withCredentials: true },
              );
              return { ...account, balance: balanceResponse.data?.balance || 0 };
            } catch {
              return { ...account, balance: 0 };
            }
          }),
        );

        const totalBalance = accountsWithBalance.reduce(
          (total, acc) => total + Number(acc.balance || 0), 0
        );
        const activeAccounts = accountsWithBalance.filter(a => a.status === "Active").length;

        setDashboard(mergeDashboard({
          user: fallbackUser,
          summary: {
            totalBalance,
            totalAccounts: accounts.length,
            ONEO_BankCoins: Math.floor(totalBalance / 1000) + activeAccounts * 50,
            notificationCount: accounts.length === 0 ? 1 : 0,
          },
          aiInsights: {
            headline: accounts.length ? "Accounts connected" : "Create your first account",
            message: accounts.length
              ? "Your balance and rewards are updating from live account data."
              : "Complete KYC and open an account to see personalized insights.",
            items: [],
          },
        }));
      } catch {
        setError(
          requestError.response?.status === 401
            ? "Please log in again to view your live dashboard."
            : "Live dashboard data is unavailable right now.",
        );
      }
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [fallbackUser]);

  useEffect(() => {
    const timeoutId = window.setTimeout(fetchDashboard, 0);
    return () => window.clearTimeout(timeoutId);
  }, [fetchDashboard]);

  const renderContent = () => {
    switch (activeView) {
      case "transactions":
        return <TransactionHistory />;
      case "open-account":
        return <OpenAccount />;
      case "kyc":
        return <KYCVerification />;
      case "admin":
        return <AdminPanel />;
      case "profile":
        return <ProfileView />;
      case "settings":
        return <SettingsView />;
      case "goals":
        return <GoalsView />;
      default:
        return (
          <>
            {error && (
              <div className="flex items-center justify-between gap-3 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 shadow-sm">
                <div className="flex items-center gap-2">
                  <AlertCircle className="size-4 shrink-0" />
                  <span>{error}</span>
                </div>
                <button
                  className="inline-flex items-center gap-2 rounded-md bg-white px-3 py-2 font-semibold text-amber-900 shadow-sm ring-1 ring-amber-200 transition hover:bg-amber-100"
                  onClick={fetchDashboard}
                  type="button"
                >
                  <RefreshCw className="size-4" />
                  Retry
                </button>
              </div>
            )}

            {loading ? (
              <DashboardSkeleton />
            ) : (
              <>
                {/* Send Money Button */}
                <div className="flex items-center justify-between">
                  <div />
                  <button
                    type="button"
                    onClick={openSendModal}
                    className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700 active:bg-indigo-800"
                  >
                    <Send className="size-4" />
                    Send Money
                  </button>
                </div>

                <StatsCards summary={dashboard.summary} />

                <section className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
                  <RecentTransactions
                    transactions={dashboard.recentTransactions}
                    onViewAll={() => setActiveView("transactions")}
                  />
                  <AIInsights insights={dashboard.aiInsights} />
                </section>

                <SpendingChart analytics={dashboard.analytics} />
              </>
            )}
          </>
        );
    }
  };

  return (
    <SidebarProvider>
      <AppSidebar
        activeView={activeView}
        onNavigate={setActiveView}
        notificationCount={dashboard.summary.notificationCount}
      />

      <SidebarInset className="min-h-screen bg-[#F5F7FB]">
        <Navbar
          user={dashboard.user}
          notificationCount={dashboard.summary.notificationCount}
          onRefresh={fetchDashboard}
          refreshing={refreshing}
          onNavigate={setActiveView}
          isDarkMode={isDarkMode}
          onToggleDarkMode={handleToggleDarkMode}
        />

        <main className="mx-auto flex w-full max-w-[1440px] flex-1 flex-col gap-5 px-4 py-5 sm:px-6 lg:px-8">
          {renderContent()}
        </main>
      </SidebarInset>

      {/* Send Money Modal */}
      {showSendModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
          <div className="relative w-full max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-2xl">
            <button
              type="button"
              onClick={() => setShowSendModal(false)}
              className="absolute right-4 top-4 rounded-md p-1 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
            >
              <X className="size-5" />
            </button>

            <div className="mb-5 flex items-center gap-3">
              <div className="flex size-10 items-center justify-center rounded-lg bg-indigo-100 text-indigo-700">
                <Send className="size-5" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-slate-950">Send Money</h2>
                <p className="text-sm text-slate-500">Transfer funds to another account</p>
              </div>
            </div>

            {sendSuccess && (
              <div className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">
                {sendSuccess}
              </div>
            )}
            {sendError && (
              <div className="mb-4 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">
                {sendError}
              </div>
            )}

            <form onSubmit={handleSendMoney} className="space-y-4">
              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">From Account</label>
                {userAccounts.length === 0 ? (
                  <p className="text-sm text-slate-500">No accounts found. Please open an account first.</p>
                ) : userAccounts.length === 1 ? (
                  <div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-700">
                    {userAccounts[0].accountType} — A/C {String(userAccounts[0]._id).slice(-6).toUpperCase()}
                  </div>
                ) : (
                  <select
                    value={sendForm.FromAccount}
                    onChange={(e) => setSendForm((prev) => ({ ...prev, FromAccount: e.target.value }))}
                    required
                    className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900 shadow-sm outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
                  >
                    <option value="">Select account</option>
                    {userAccounts.map((acc) => (
                      <option key={acc._id} value={acc._id}>
                        {acc.accountType} — A/C {String(acc._id).slice(-6).toUpperCase()}
                      </option>
                    ))}
                  </select>
                )}
              </div>

              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">To Account ID</label>
                <input
                  type="text"
                  value={sendForm.toAccount}
                  onChange={(e) => setSendForm((prev) => ({ ...prev, toAccount: e.target.value }))}
                  required
                  placeholder="Enter recipient account ID"
                  className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900 shadow-sm outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
                />
              </div>

              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">Amount (₹)</label>
                <input
                  type="number"
                  min="1"
                  step="any"
                  value={sendForm.amount}
                  onChange={(e) => setSendForm((prev) => ({ ...prev, amount: e.target.value }))}
                  required
                  placeholder="Enter amount"
                  className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900 shadow-sm outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
                />
              </div>

              <div className="flex gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setShowSendModal(false)}
                  className="flex-1 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm transition hover:bg-slate-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={sendLoading || userAccounts.length === 0 || !sendForm.FromAccount}
                  className="flex-1 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {sendLoading ? "Processing..." : "Send Money"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </SidebarProvider>
  );
};

export default Home;

// Frontend_Angular/src/app/components/home.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../services/api.service';
import {
  LucideArrowRightLeft,
  LucideBell,
  LucideChevronDown,
  LucideLandmark,
  LucideLayoutDashboard,
  LucideLogOut,
  LucideMenu,
  LucideMoon,
  LucidePiggyBank,
  LucideRotateCw,
  LucideSend,
  LucideSettings,
  LucideShield,
  LucideShieldCheck,
  LucideShieldCog,
  LucideSun,
  LucideUserRound,
  LucideUsersRound,
  LucideX
} from '@lucide/angular';

// Import subviews
import { GlobalSearchComponent } from './dashboard/global-search.component';
import { StatsCardsComponent } from './dashboard/stats-cards.component';
import { RecentTransactionsComponent } from './dashboard/recent-transactions.component';
import { SpendingChartComponent } from './dashboard/spending-chart.component';
import { AiInsightsComponent } from './dashboard/ai-insights.component';
import { TransactionsViewComponent } from './dashboard/transactions.component';
import { OpenAccountViewComponent } from './dashboard/open-account.component';
import { KycVerificationViewComponent } from './dashboard/kyc.component';
import { BeneficiariesViewComponent } from './dashboard/beneficiaries.component';
import { GoalsViewComponent } from './dashboard/goals.component';
import { ProfileViewComponent } from './dashboard/profile.component';
import { SettingsViewComponent } from './dashboard/settings.component';
import { AdminPanelComponent } from './dashboard/admin.component';
import { TranslatePipe } from '../pipes/translate.pipe';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    LucideArrowRightLeft,
    LucideBell,
    LucideChevronDown,
    LucideLandmark,
    LucideLayoutDashboard,
    LucideLogOut,
    LucideMenu,
    LucideMoon,
    LucidePiggyBank,
    LucideRotateCw,
    LucideSend,
    LucideSettings,
    LucideShield,
    LucideShieldCheck,
    LucideShieldCog,
    LucideSun,
    LucideUserRound,
    LucideUsersRound,
    LucideX,
    GlobalSearchComponent,
    StatsCardsComponent,
    RecentTransactionsComponent,
    SpendingChartComponent,
    AiInsightsComponent,
    TransactionsViewComponent,
    OpenAccountViewComponent,
    KycVerificationViewComponent,
    BeneficiariesViewComponent,
    GoalsViewComponent,
    ProfileViewComponent,
    SettingsViewComponent,
    AdminPanelComponent,
    TranslatePipe
  ],
  template: `
    <div [class.dark]="isDarkMode()" class="min-h-screen bg-slate-50 text-slate-900 transition-colors duration-300 dark:bg-slate-900 dark:text-slate-100 md:flex">
      <!-- Mobile backdrop -->
      <button
        *ngIf="mobileSidebarOpen()"
        type="button"
        aria-label="Close navigation"
        class="fixed inset-0 z-30 bg-slate-950/60 backdrop-blur-[2px] md:hidden"
        (click)="mobileSidebarOpen.set(false)"
      ></button>

      <!-- SIDEBAR -->
      <aside
        [ngClass]="mobileSidebarOpen() ? 'translate-x-0' : '-translate-x-full md:translate-x-0'"
        class="fixed inset-y-0 left-0 z-40 flex w-[min(18rem,86vw)] shrink-0 flex-col justify-between border-r border-slate-800 bg-[#0b132b] text-white shadow-2xl transition-transform duration-200 md:sticky md:top-0 md:h-screen md:w-64 md:shadow-none"
      >
        <div>
          <!-- Branding Header -->
          <div class="h-20 flex items-center px-6 border-b border-slate-800/80">
            <div class="w-8 h-10 bg-gradient-to-tr from-indigo-500 via-purple-500 to-pink-500 rounded-xl flex items-center justify-center font-black text-white text-lg shadow-md shadow-indigo-500/20 mr-3 cursor-default">
              Y
            </div>
            <div>
              <span class="block font-black tracking-wider text-white text-lg leading-none">YONO App</span>
              <span class="block text-[9px] tracking-widest text-slate-400 font-bold uppercase mt-1">Secure Banking</span>
            </div>
          </div>

          <!-- Navigation Links -->
          <nav class="p-4 space-y-1.5">
            <button
              *ngFor="let link of sidebarLinks"
              type="button"
              (click)="navigateTo(link.id)"
              [ngClass]="activeView() === link.id ? 'bg-indigo-600/90 text-white font-extrabold shadow-sm shadow-indigo-600/30' : 'text-slate-300 hover:bg-slate-900/80 hover:text-white'"
              class="w-full flex items-center gap-3.5 px-4 py-3 rounded-xl text-xs font-semibold transition text-left"
            >
              <svg *ngIf="link.id === 'dashboard'" lucideLayoutDashboard class="size-4.5"></svg>
              <svg *ngIf="link.id === 'transactions'" lucideArrowRightLeft class="size-4.5"></svg>
              <svg *ngIf="link.id === 'open-account'" lucideLandmark class="size-4.5"></svg>
              <svg *ngIf="link.id === 'kyc'" lucideShieldCheck class="size-4.5"></svg>
              <svg *ngIf="link.id === 'beneficiaries'" lucideUsersRound class="size-4.5"></svg>
              <svg *ngIf="link.id === 'goals'" lucidePiggyBank class="size-4.5"></svg>
              <svg *ngIf="link.id === 'profile'" lucideUserRound class="size-4.5"></svg>
              <svg *ngIf="link.id === 'settings'" lucideSettings class="size-4.5"></svg>
              <span>{{ link.key | translate }}</span>
            </button>

            <!-- Admin Console Link -->
            <button
              *ngIf="isAdmin()"
              type="button"
              (click)="navigateTo('admin')"
              [ngClass]="activeView() === 'admin' ? 'bg-rose-600 text-white font-extrabold' : 'text-rose-400 hover:bg-rose-950/40 hover:text-rose-300'"
              class="w-full flex items-center gap-3.5 px-4 py-3 rounded-xl text-xs font-bold transition text-left border border-dashed border-rose-800/50 mt-4"
            >
              <svg lucideShieldCog class="size-4.5"></svg>
              <span>{{ 'nav.admin' | translate }}</span>
            </button>
          </nav>
        </div>

        <!-- Footer Session Badge & Logout -->
        <div class="p-4 space-y-3 border-t border-slate-800/80">
          <!-- Protected Session Indicator -->
          <div class="flex items-center gap-3 rounded-xl border border-slate-800/80 bg-slate-900/60 p-3">
            <div class="flex size-8 shrink-0 items-center justify-center rounded-lg bg-emerald-950/60 text-emerald-400">
              <svg lucideShield class="size-4"></svg>
            </div>
            <div class="min-w-0">
              <p class="text-xs font-bold text-white leading-tight">Protected Session</p>
              <p class="text-[10px] text-slate-400 leading-tight">Bank-grade controls active</p>
            </div>
          </div>

          <!-- User & Logout Footer -->
          <div class="flex items-center justify-between pt-1">
            <div class="min-w-0">
              <p class="text-xs font-bold text-white truncate">{{ userDisplayName }}</p>
              <p class="text-[10px] text-slate-400 truncate">{{ user()?.email }}</p>
            </div>
            <button
              type="button"
              (click)="handleLogout()"
              aria-label="Log out"
              title="Log out"
              class="ml-2 inline-flex shrink-0 items-center gap-1 rounded-lg px-2.5 py-1.5 text-xs font-bold text-rose-400 hover:bg-rose-950/50 hover:text-rose-300 transition"
            >
              <svg lucideLogOut class="size-4"></svg>
              <span class="sr-only sm:not-sr-only">{{ 'header.logout' | translate }}</span>
            </button>
          </div>
        </div>
      </aside>

      <!-- MAIN CONTENT AREA -->
      <div class="flex min-h-screen min-w-0 flex-1 flex-col">
        <!-- TOP NAVBAR -->
        <header class="sticky top-0 z-20 flex min-h-20 items-center justify-between gap-4 border-b border-slate-200/80 bg-white/90 px-4 py-3 backdrop-blur-md dark:border-slate-800 dark:bg-slate-950/90 sm:px-6 lg:px-8">
          <!-- Left: Mobile Menu & Welcome Banner -->
          <div class="flex min-w-0 items-center gap-3 sm:gap-4">
            <button
              type="button"
              aria-label="Open navigation"
              class="inline-flex size-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-100 dark:border-slate-800 dark:text-slate-300 dark:hover:bg-slate-900 md:hidden"
              (click)="mobileSidebarOpen.set(true)"
            >
              <svg lucideMenu class="size-5"></svg>
            </button>

            <!-- Welcome Header -->
            <div class="min-w-0">
              <h1 class="truncate text-base font-black tracking-tight text-slate-900 dark:text-white sm:text-xl">
                {{ 'header.welcome' | translate }}, {{ userDisplayName }}
              </h1>
              <p class="hidden text-xs font-medium text-slate-500 dark:text-slate-400 sm:block">
                Your secure YONO App banking overview is live.
              </p>
            </div>
          </div>

          <!-- Middle & Right Controls -->
          <div class="flex shrink-0 items-center gap-2 sm:gap-3">
            <!-- Universal Global Search Component -->
            <app-global-search (onSelectResult)="navigateTo($event)"></app-global-search>

            <!-- Refresh Button -->
            <button
              type="button"
              (click)="refreshData()"
              [disabled]="loading()"
              aria-label="Refresh data"
              title="Refresh dashboard"
              class="inline-flex size-10 items-center justify-center rounded-xl border border-slate-200 text-slate-600 transition hover:bg-slate-100 dark:border-slate-800 dark:text-slate-300 dark:hover:bg-slate-900"
            >
              <svg lucideRotateCw [ngClass]="{ 'animate-spin': loading() }" class="size-4.5"></svg>
            </button>

            <!-- Notification Bell -->
            <button
              type="button"
              aria-label="Notifications"
              title="Notifications"
              class="relative inline-flex size-10 items-center justify-center rounded-xl border border-slate-200 text-slate-600 transition hover:bg-slate-100 dark:border-slate-800 dark:text-slate-300 dark:hover:bg-slate-900"
            >
              <svg lucideBell class="size-4.5"></svg>
              <span class="absolute top-2 right-2 size-2 rounded-full bg-indigo-600 ring-2 ring-white dark:ring-slate-950"></span>
            </button>

            <!-- Theme Toggle -->
            <button
              type="button"
              (click)="toggleTheme()"
              [attr.aria-label]="isDarkMode() ? 'Switch to light mode' : 'Switch to dark mode'"
              [attr.title]="isDarkMode() ? 'Switch to light mode' : 'Switch to dark mode'"
              class="inline-flex size-10 items-center justify-center rounded-xl border border-slate-200 text-slate-600 transition hover:bg-slate-100 dark:border-slate-800 dark:text-slate-300 dark:hover:bg-slate-900"
            >
              <svg *ngIf="isDarkMode()" lucideSun class="size-4.5 text-amber-400"></svg>
              <svg *ngIf="!isDarkMode()" lucideMoon class="size-4.5"></svg>
            </button>

            <!-- User Avatar Circle -->
            <div class="hidden items-center gap-2 rounded-full border border-slate-200 p-1 dark:border-slate-800 sm:flex">
              <div class="flex size-8 items-center justify-center rounded-full bg-indigo-600 font-extrabold text-white text-xs shadow-sm">
                {{ userInitial }}
              </div>
            </div>

            <!-- Send Money Primary Action Button -->
            <button
              *ngIf="activeView() === 'dashboard'"
              type="button"
              (click)="openSendMoneyModal()"
              class="inline-flex min-h-10 items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-extrabold text-white shadow-md shadow-indigo-600/20 transition hover:bg-indigo-700 sm:text-sm"
            >
              <svg lucideSend class="size-4"></svg>
              <span class="hidden sm:inline">Send Money</span>
              <span class="sm:hidden">Send</span>
            </button>
          </div>
        </header>

        <!-- ROUTED CONTENT CONTAINER -->
        <main class="flex-1 overflow-y-auto bg-slate-50/70 px-4 py-6 dark:bg-slate-900 dark:text-slate-100 sm:px-6 lg:px-8">
          <div class="mx-auto w-full max-w-[1440px]">
            <!-- SKELETON / LOADING -->
            <div *ngIf="loading() && activeView() === 'dashboard'" class="space-y-6">
              <div class="grid gap-4 md:grid-cols-4">
                <div *ngFor="let x of [1,2,3,4]" class="h-32 animate-pulse rounded-2xl bg-white border border-slate-200 shadow-sm dark:bg-slate-950 dark:border-slate-800"></div>
              </div>
              <div class="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
                <div class="h-96 animate-pulse rounded-2xl bg-white border border-slate-200 shadow-sm dark:bg-slate-950"></div>
                <div class="h-96 animate-pulse rounded-2xl bg-white border border-slate-200 shadow-sm dark:bg-slate-950"></div>
              </div>
            </div>

            <!-- DASHBOARD CONTAINER VIEW -->
            <div *ngIf="!loading() && activeView() === 'dashboard'" class="space-y-6">
              <!-- Statistics Cards -->
              <app-stats-cards [summary]="dashboard()?.summary"></app-stats-cards>

              <!-- Inner Dashboard Sections -->
              <div class="grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
                <app-recent-transactions
                  [transactions]="dashboard()?.recentTransactions"
                  (onViewAll)="navigateTo('transactions')"
                ></app-recent-transactions>

                <app-ai-insights [insights]="dashboard()?.aiInsights"></app-ai-insights>
              </div>

              <!-- Spending Analytics -->
              <app-spending-chart [analytics]="dashboard()?.analytics"></app-spending-chart>
            </div>

            <!-- OTHER DYNAMIC VIEWS -->
            <app-transactions-view *ngIf="activeView() === 'transactions'"></app-transactions-view>
            <app-open-account-view *ngIf="activeView() === 'open-account'"></app-open-account-view>
            <app-kyc-verification-view *ngIf="activeView() === 'kyc'"></app-kyc-verification-view>
            <app-beneficiaries-view *ngIf="activeView() === 'beneficiaries'"></app-beneficiaries-view>
            <app-goals-view *ngIf="activeView() === 'goals'"></app-goals-view>
            <app-profile-view *ngIf="activeView() === 'profile'"></app-profile-view>
            <app-settings-view *ngIf="activeView() === 'settings'" (onThemeChange)="handleThemeChange($event)"></app-settings-view>
            <app-admin-panel *ngIf="activeView() === 'admin'"></app-admin-panel>
          </div>
        </main>
      </div>

      <!-- SEND MONEY MODAL -->
      <div *ngIf="showSendModal()" class="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-0 backdrop-blur-sm sm:items-center sm:p-4">
        <div class="relative max-h-[92vh] w-full overflow-y-auto rounded-t-2xl border border-slate-200 bg-white p-6 shadow-2xl dark:border-slate-800 dark:bg-slate-950 sm:max-w-md sm:rounded-2xl">
          <button
            type="button"
            (click)="showSendModal.set(false)"
            aria-label="Close dialog"
            class="absolute right-4 top-4 rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800 dark:hover:text-white"
          >
            <svg lucideX class="size-5"></svg>
          </button>

          <h2 class="text-lg font-extrabold text-slate-950 dark:text-white mb-1">Send Money</h2>
          <p class="text-xs font-medium text-slate-500 mb-5">Transfer funds securely to another account</p>

          <div *ngIf="sendError()" class="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3.5 text-xs font-bold text-rose-700 dark:border-rose-900/50 dark:bg-rose-950/40 dark:text-rose-300">
            {{ sendError() }}
          </div>
          <div *ngIf="sendSuccess()" class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3.5 text-xs font-bold text-emerald-700 dark:border-emerald-900/50 dark:bg-emerald-950/40 dark:text-emerald-300">
            {{ sendSuccess() }}
          </div>

          <form (submit)="handleSendMoney($event)" class="space-y-4">
            <!-- Source Account -->
            <div>
              <label for="fromAcc" class="block text-xs font-bold text-slate-700 dark:text-slate-300">From Account</label>
              <select
                id="fromAcc"
                name="fromAccount"
                required
                [(ngModel)]="sendForm.fromAccount"
                class="mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-xs font-medium text-slate-900 focus:border-indigo-500 focus:outline-none dark:border-slate-800 dark:bg-slate-900 dark:text-white"
              >
                <option value="">Select source account</option>
                <option *ngFor="let acc of userAccounts()" [value]="acc.id">
                  {{ acc.accountType }} - A/C {{ acc.id.slice(-6).toUpperCase() }} (Bal: ₹{{ acc.balance | number:'1.0-0' }})
                </option>
              </select>
            </div>

            <!-- Destination Account -->
            <div>
              <label for="toAcc" class="block text-xs font-bold text-slate-700 dark:text-slate-300">To Account ID (GUID)</label>
              <input
                id="toAcc"
                type="text"
                name="toAccount"
                required
                [(ngModel)]="sendForm.toAccount"
                class="mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-xs font-medium text-slate-900 dark:border-slate-800 dark:bg-slate-900 dark:text-white"
                placeholder="Paste destination account GUID"
              />
            </div>

            <!-- Amount -->
            <div>
              <label for="sendAmt" class="block text-xs font-bold text-slate-700 dark:text-slate-300">Amount (INR)</label>
              <input
                id="sendAmt"
                type="number"
                name="amount"
                required
                min="1"
                [(ngModel)]="sendForm.amount"
                class="mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-xs font-medium text-slate-900 dark:border-slate-800 dark:bg-slate-900 dark:text-white"
                placeholder="₹1,000"
              />
            </div>

            <div class="pt-2">
              <button
                type="submit"
                [disabled]="modalLoading() || sendForm.amount <= 0 || !sendForm.fromAccount || !sendForm.toAccount"
                class="w-full rounded-xl bg-indigo-600 py-3 text-xs font-extrabold text-white shadow-md shadow-indigo-600/20 hover:bg-indigo-700 disabled:opacity-50 transition"
              >
                {{ modalLoading() ? 'Processing Transfer...' : 'Transfer Funds' }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `
})
export class HomeComponent implements OnInit {
  private readonly apiService = inject(ApiService);
  private readonly router = inject(Router);

  protected activeView = signal('dashboard');
  protected loading = signal(true);
  protected dashboard = signal<any>(null);
  protected user = signal<any>(null);

  protected isDarkMode = signal(false);
  protected mobileSidebarOpen = signal(false);

  // Send Money Modal State
  protected showSendModal = signal(false);
  protected modalLoading = signal(false);
  protected userAccounts = signal<any[]>([]);
  protected sendError = signal('');
  protected sendSuccess = signal('');

  protected sendForm = {
    fromAccount: '',
    toAccount: '',
    amount: 0
  };

  protected sidebarLinks = [
    { id: 'dashboard', key: 'nav.dashboard' },
    { id: 'transactions', key: 'nav.transactions' },
    { id: 'open-account', key: 'nav.openAccount' },
    { id: 'kyc', key: 'nav.kyc' },
    { id: 'beneficiaries', key: 'nav.beneficiaries' },
    { id: 'goals', key: 'nav.goals' },
    { id: 'profile', key: 'nav.profile' },
    { id: 'settings', key: 'nav.settings' }
  ];

  ngOnInit() {
    this.checkUserSession();
    this.fetchDashboardData();
    this.loadTheme();
  }

  protected get userDisplayName(): string {
    const u = this.user();
    if (!u) return 'User';
    return u.username || u.userName || u.name || (u.email ? u.email.split('@')[0] : 'User');
  }

  protected get userInitial(): string {
    const name = this.userDisplayName;
    return name && name.length > 0 ? name[0].toUpperCase() : 'U';
  }

  private checkUserSession() {
    const stored = sessionStorage.getItem('YONO AppUser');
    if (stored) {
      try {
        this.user.set(JSON.parse(stored));
      } catch {
        // ignore
      }
    }
  }

  protected isAdmin(): boolean {
    const role = this.user()?.role;
    return role === 'admin';
  }

  protected refreshData() {
    this.fetchDashboardData();
  }

  protected fetchDashboardData() {
    this.loading.set(true);
    this.apiService.getDashboard().subscribe({
      next: (res) => {
        this.dashboard.set(res);
        if (res.user) {
          this.user.set(res.user);
        }
        this.loading.set(false);
      },
      error: (err) => {
        this.loading.set(false);
        if (err.status === 401) {
          this.router.navigate(['/login']);
        }
      }
    });
  }

  protected navigateTo(viewId: string) {
    if (viewId === 'admin' && !this.isAdmin()) {
      this.activeView.set('dashboard');
      this.mobileSidebarOpen.set(false);
      return;
    }
    this.activeView.set(viewId);
    this.mobileSidebarOpen.set(false);
  }

  protected handleLogout() {
    this.apiService.logout().subscribe({
      next: () => {
        sessionStorage.removeItem('YONO AppUser');
        this.router.navigate(['/login']);
      },
      error: () => {
        sessionStorage.removeItem('YONO AppUser');
        this.router.navigate(['/login']);
      }
    });
  }

  protected openSendMoneyModal() {
    this.sendForm.fromAccount = '';
    this.sendForm.toAccount = '';
    this.sendForm.amount = 0;
    this.sendError.set('');
    this.sendSuccess.set('');
    this.userAccounts.set([]);
    this.showSendModal.set(true);

    this.apiService.getAccountDetails().subscribe({
      next: (res) => {
        this.userAccounts.set(res.accounts || []);
      },
      error: () => {
        this.sendError.set('Failed to fetch source accounts');
      }
    });
  }

  protected handleSendMoney(event: Event) {
    event.preventDefault();
    this.modalLoading.set(true);
    this.sendError.set('');
    this.sendSuccess.set('');

    const idempotencyKey = `transfer-${this.sendForm.fromAccount}-${Date.now()}`;

    this.apiService.createTransaction({
      FromAccount: this.sendForm.fromAccount,
      toAccount: this.sendForm.toAccount,
      amount: this.sendForm.amount,
      idempotencyKey: idempotencyKey
    }).subscribe({
      next: (res) => {
        this.modalLoading.set(false);
        this.sendSuccess.set(res.message || 'Transfer completed successfully!');
        this.fetchDashboardData();
        setTimeout(() => {
          this.showSendModal.set(false);
        }, 1500);
      },
      error: (err) => {
        this.modalLoading.set(false);
        this.sendError.set(err.error?.message || 'Transfer failed. Check details and balance.');
      }
    });
  }

  // Theme support
  protected loadTheme() {
    const saved = localStorage.getItem('yono_theme');
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    this.applyTheme(saved ? saved === 'dark' : prefersDark);
  }

  protected toggleTheme() {
    const dark = !this.isDarkMode();
    this.applyTheme(dark);
    localStorage.setItem('yono_theme', dark ? 'dark' : 'light');
  }

  protected handleThemeChange(dark: boolean) {
    this.applyTheme(dark);
    localStorage.setItem('yono_theme', dark ? 'dark' : 'light');
  }

  private applyTheme(dark: boolean) {
    this.isDarkMode.set(dark);
    document.documentElement.classList.toggle('dark', dark);
  }
}
