// Frontend_Angular/src/app/components/dashboard/stats-cards.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  LucideWallet,
  LucideTrendingUp,
  LucideTrendingDown,
  LucideCoins
} from '@lucide/angular';
import { TranslatePipe } from '../../pipes/translate.pipe';

@Component({
  selector: 'app-stats-cards',
  standalone: true,
  imports: [
    CommonModule,
    LucideWallet,
    LucideTrendingUp,
    LucideTrendingDown,
    LucideCoins,
    TranslatePipe
  ],
  template: `
    <div class="grid gap-4 sm:gap-5 md:grid-cols-2 xl:grid-cols-4">
      <!-- Card 1: Total Balance -->
      <div class="group relative flex flex-col justify-between rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm transition-all duration-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-950">
        <div class="flex items-start justify-between gap-3">
          <div>
            <span class="text-xs font-semibold text-slate-500 dark:text-slate-400">{{ 'stats.totalBalance' | translate }}</span>
            <h3 class="mt-1.5 text-2xl font-extrabold tracking-tight text-slate-900 dark:text-white sm:text-3xl">
              ₹{{ (summary?.totalBalance || 0) | number:'1.2-2' }}
            </h3>
          </div>
          <div class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-purple-100 text-purple-600 dark:bg-purple-950/60 dark:text-purple-300">
            <svg lucideWallet class="size-5"></svg>
          </div>
        </div>
        <div class="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs dark:border-slate-800/80">
          <span class="truncate text-slate-400 dark:text-slate-500">{{ summary?.totalAccounts || 1 }} {{ 'stats.activeAccounts' | translate | lowercase }}</span>
          <span class="inline-flex items-center gap-1 font-bold text-emerald-600 dark:text-emerald-400">
            <svg lucideTrendingUp class="size-3.5"></svg>
            0%
          </span>
        </div>
      </div>

      <!-- Card 2: Total Income -->
      <div class="group relative flex flex-col justify-between rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm transition-all duration-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-950">
        <div class="flex items-start justify-between gap-3">
          <div>
            <span class="text-xs font-semibold text-slate-500 dark:text-slate-400">{{ 'stats.monthlyIncome' | translate }}</span>
            <h3 class="mt-1.5 text-2xl font-extrabold tracking-tight text-slate-900 dark:text-white sm:text-3xl">
              ₹{{ (summary?.totalIncome || 0) | number:'1.2-2' }}
            </h3>
          </div>
          <div class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-emerald-100 text-emerald-600 dark:bg-emerald-950/60 dark:text-emerald-300">
            <svg lucideTrendingUp class="size-5"></svg>
          </div>
        </div>
        <div class="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs dark:border-slate-800/80">
          <span class="truncate text-slate-400 dark:text-slate-500">{{ 'common.completed' | translate }}</span>
          <span class="inline-flex items-center gap-1 font-bold text-emerald-600 dark:text-emerald-400">
            <svg lucideTrendingUp class="size-3.5"></svg>
            0%
          </span>
        </div>
      </div>

      <!-- Card 3: Total Expense -->
      <div class="group relative flex flex-col justify-between rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm transition-all duration-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-950">
        <div class="flex items-start justify-between gap-3">
          <div>
            <span class="text-xs font-semibold text-slate-500 dark:text-slate-400">{{ 'stats.monthlyExpenses' | translate }}</span>
            <h3 class="mt-1.5 text-2xl font-extrabold tracking-tight text-slate-900 dark:text-white sm:text-3xl">
              ₹{{ (summary?.totalExpense || 0) | number:'1.2-2' }}
            </h3>
          </div>
          <div class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-rose-100 text-rose-600 dark:bg-rose-950/60 dark:text-rose-300">
            <svg lucideTrendingDown class="size-5"></svg>
          </div>
        </div>
        <div class="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs dark:border-slate-800/80">
          <span class="truncate text-slate-400 dark:text-slate-500">{{ 'common.completed' | translate }}</span>
          <span class="inline-flex items-center gap-1 font-bold text-emerald-600 dark:text-emerald-400">
            <svg lucideTrendingUp class="size-3.5"></svg>
            0%
          </span>
        </div>
      </div>

      <!-- Card 4: YONO Coins -->
      <div class="group relative flex flex-col justify-between rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm transition-all duration-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-950">
        <div class="flex items-start justify-between gap-3">
          <div>
            <span class="text-xs font-semibold text-slate-500 dark:text-slate-400">YONO Coins</span>
            <h3 class="mt-1.5 text-2xl font-extrabold tracking-tight text-slate-900 dark:text-white sm:text-3xl">
              {{ summary?.oneo_BankCoins || summary?.oNEO_BankCoins || 0 }}
            </h3>
          </div>
          <div class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-600 dark:bg-amber-950/60 dark:text-amber-300">
            <svg lucideCoins class="size-5"></svg>
          </div>
        </div>
        <div class="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs dark:border-slate-800/80">
          <span class="truncate text-slate-400 dark:text-slate-500">0 earned</span>
          <span class="inline-flex items-center gap-1 font-bold text-emerald-600 dark:text-emerald-400">
            <svg lucideTrendingUp class="size-3.5"></svg>
            +0
          </span>
        </div>
      </div>
    </div>
  `
})
export class StatsCardsComponent {
  @Input() summary: any = {};
}

// Frontend/src/Components/Dashboard/StatsCards.jsx
import {
  ArrowDownRight,
  ArrowUpRight,
  Coins,
  TrendingDown,
  TrendingUp,
  WalletCards,
} from "lucide-react";

const currencyFormatter = new Intl.NumberFormat("en-IN", {
  style: "currency",
  currency: "INR",
  maximumFractionDigits: 2,
});

const numberFormatter = new Intl.NumberFormat("en-IN");

const cardStyles = {
  balance: {
    icon: WalletCards,
    iconClass: "bg-violet-100 text-violet-700 ring-violet-200",
    glowClass: "from-violet-500/10",
  },
  income: {
    icon: TrendingUp,
    iconClass: "bg-emerald-100 text-emerald-700 ring-emerald-200",
    glowClass: "from-emerald-500/10",
  },
  expense: {
    icon: TrendingDown,
    iconClass: "bg-rose-100 text-rose-700 ring-rose-200",
    glowClass: "from-rose-500/10",
  },
  coins: {
    icon: Coins,
    iconClass: "bg-amber-100 text-amber-700 ring-amber-200",
    glowClass: "from-amber-500/10",
  },
};

function formatTrend(value, mode) {
  const safeValue = Number(value || 0);
  const positiveTrend = safeValue >= 0;
  const goodTrend = mode === "expense" ? safeValue <= 0 : safeValue >= 0;
  const Icon = positiveTrend ? ArrowUpRight : ArrowDownRight;

  return {
    Icon,
    label: `${Math.abs(safeValue).toLocaleString("en-IN", {
      maximumFractionDigits: 1,
    })}% from last month`,
    className: goodTrend ? "text-emerald-600" : "text-rose-600",
  };
}

export default function StatsCards({ summary }) {
  const cards = [
    {
      key: "balance",
      title: "Total Balance",
      value: currencyFormatter.format(summary.totalBalance || 0),
      detail: `${summary.totalAccounts || 0} connected account${summary.totalAccounts === 1 ? "" : "s"}`,
      change: summary.balanceChange,
    },
    {
      key: "income",
      title: "Total Income",
      value: currencyFormatter.format(summary.totalIncome || 0),
      detail: "Completed credits",
      change: summary.incomeChange,
    },
    {
      key: "expense",
      title: "Total Expense",
      value: currencyFormatter.format(summary.totalExpense || 0),
      detail: "Completed debits",
      change: summary.expenseChange,
    },
    {
      key: "coins",
      title: "YONO App Coins",
      value: numberFormatter.format(summary.ONEO_BankCoins || 0),
      detail: `${numberFormatter.format(summary.coinsChange || 0)} earned this week`,
      change: summary.coinsChange ? 100 : 0,
      isCoinCard: true,
    },
  ];

  return (
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      {cards.map((card) => {
        const style = cardStyles[card.key];
        const Icon = style.icon;
        const trend = formatTrend(card.change, card.key);

        return (
          <article
            className="relative overflow-hidden rounded-lg border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"
            key={card.key}
          >
            <div className={`absolute inset-x-0 top-0 h-20 bg-gradient-to-b ${style.glowClass} to-transparent`} />
            <div className="relative flex items-start justify-between gap-4">
              <div className="min-w-0">
                <p className="text-sm font-medium text-slate-500">{card.title}</p>
                <h2 className="mt-2 break-words text-2xl font-bold tracking-normal text-slate-950">
                  {card.value}
                </h2>
              </div>

              <div className={`flex size-12 shrink-0 items-center justify-center rounded-lg ring-1 ${style.iconClass}`}>
                <Icon className="size-6" />
              </div>
            </div>

            <div className="relative mt-5 flex items-center justify-between gap-3 text-sm">
              <span className="truncate text-slate-500">{card.detail}</span>
              <span className={`inline-flex shrink-0 items-center gap-1 font-semibold ${card.isCoinCard ? "text-emerald-600" : trend.className}`}>
                {card.isCoinCard ? <ArrowUpRight className="size-4" /> : <trend.Icon className="size-4" />}
                {card.isCoinCard ? `+${numberFormatter.format(summary.coinsChange || 0)}` : trend.label}
              </span>
            </div>
          </article>
        );
      })}
    </section>
  );
}
